# Replace these IPs with your VM public IPs.
# node_ip should be each VM private IP if available. If you do not know it, remove node_ip and Ansible will use default IPv4.

[rke2_servers]
rke2-1 ansible_host=20.244.31.172 node_ip=10.0.0.4
rke2-2 ansible_host=98.70.38.21  node_ip=10.0.0.5
rke2-3 ansible_host=<NODE_3_PUBLIC_IP> node_ip=10.0.0.6

[all:vars]
ansible_user=azureuser
ansible_become=true
ansible_python_interpreter=/usr/bin/python3

# Uncomment and update this if you use a private key.
# ansible_ssh_private_key_file=~/.ssh/key.pem

# For labs only if you are getting "Host key verification failed".
# Production recommendation: use ssh-keyscan instead of disabling host checking.
# ansible_ssh_common_args='-o StrictHostKeyChecking=no'
